dist: precise
sudo: false

language: c

addons:
  apt:
    sources:
       - george-edison55-precise-backports # cmake 3.2.3
    packages:
      - cmake
      - cmake-data
      - yasm
      - check
      - libdbus-1-dev
      - libopenal-dev
      - libopenal-data
      - libopenal1
      - libv4l-dev
      - mingw-w64
      - mingw-w64-dev
      - binutils-mingw-w64
      - gcc-mingw-w64

cache:
  directories:
    - $HOME/cache

matrix:
  # allow_failures:
  #   - os: osx
  fast_finish: true
  include:
    - os: linux
      env: BUILD=linux
      compiler: clang

    - os: linux
      sudo: required
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - mingw-w64
            - gcc-mingw-w64
            - mingw-w64-common
            - binutils-mingw-w64
            - yasm
            - libopenal-dev
            - libopenal-data
            - libopenal1
      env: BUILD=windows TOXCORE_REPO_BRANCH="master"
      compiler: x86_64-w64-mingw32-gcc

    - os: linux
      sudo: required
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - mingw-w64
            - gcc-mingw-w64
            - mingw-w64-common
            - binutils-mingw-w64
            - yasm
            - libopenal-dev
            - libopenal-data
            - libopenal1
      env: BUILD=windows_legacy
      compiler: i686-w64-mingw32-gcc

    - os: osx
      compiler: clang
      env: BUILD=osx TOXCORE_REPO_BRANCH="v0.1.4"

    # We don't support old toxcore yet/anymore
    # - os: linux
    #   env: BUILD=linux TOXCORE_REPO=irungentoo/toxcore
    #   compiler: gcc
    # - os: linux
    #   env: BUILD=linux TOXCORE_REPO=irungentoo/toxcore
    #   compiler: clang

git:
  depth: 5

before_script:
  - ./extra/travis/env.sh
  - ./extra/travis/${BUILD}-before.sh
  - ./extra/travis/filter_audio.sh

script:
  - ./extra/travis/${BUILD}-script.sh

after_failure:
  - ./extra/travis/debug_failure.sh


notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#utox"
    template:
      - "TRAVIS #%{build_number} %{result} %{repository_name} %{build_url}"

branches:
  only:
    - master
    - develop
