sudo: false

language: c

addons:
  apt:
    packages:
      - cmake
      - cmake-data
      - yasm
      - check
      - libdbus-1-dev
      - libopenal-dev
      - libopenal-data
      - libopenal1
      - libv4l-dev

cache:
  directories:
    - $HOME/cache

matrix:
  fast_finish: true
  include:
    - name: "Linux Clang"
      os: linux
      env: BUILD=linux
      compiler: clang

    - name: "Windows x64"
      sudo: required
      os: linux
      env: BUILD=windows
      compiler: x86_64-w64-mingw32-gcc
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc
            - mingw-w64
            - gcc-mingw-w64
            - mingw-w64-common
            - binutils-mingw-w64
            - yasm
            - libopenal-dev
            - libopenal-data
            - libopenal1

    - name: "Windows x32 (XP)"
      sudo: required
      os: linux
      env: BUILD=windows_legacy
      compiler: i686-w64-mingw32-gcc
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc
            - mingw-w64
            - gcc-mingw-w64
            - mingw-w64-common
            - binutils-mingw-w64
            - yasm
            - libopenal-dev
            - libopenal-data
            - libopenal1

    - os: osx
      compiler: clang
      env: BUILD=osx

git:
  depth: 5

before_script:
  - ./extra/travis/env.sh
  - ./extra/travis/${BUILD}-before.sh
  - ./extra/travis/filter_audio.sh

script:
  - ./extra/travis/${BUILD}-script.sh

after_failure:
  - ./extra/travis/debug_failure.sh


notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#utox"
    use_notice: true
    skip_join: true
    template:
      - "TRAVIS Build %{result} %{branch} %{message} %{build_url}"


