dist: trusty

language: c


matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILD=linux
      addons:
        apt:
          packages:
            - yasm
            - check
            - libopenal-dev
            - libopenal-data
            - libopenal1
            - dbus
            - libdbus-1-3
            - libv4l-dev
    - os: linux
      compiler: clang
      env: BUILD=linux
      addons:
              apt:
                packages:
                  - yasm
                  - check
                  - libopenal-dev
                  - libopenal-data
                  - libopenal1
                  - dbus
                  - libdbus-1-3
                  - libv4l-dev
    - os: linux
      compiler: x86_64-w64-mingw32-gcc
      env: BUILD=windows
      addons:
        apt:
          packages:
            - libopenal-dev
            - mingw-w64
            - mingw-w64-dev
            - mingw-w64-common
            - binutils-mingw-w64
    - os: osx
      compiler: clang
      env: BUILD=osx

git:
  depth: 5


before_script:
  - if [ "$BUILD" = "linux"   ]; then ./travis/linux-before.sh;   fi
  - if [ "$BUILD" = "osx"     ]; then ./travis/osx-before.sh;     fi
  - if [ "$BUILD" = "windows" ]; then ./travis/windows-before.sh; fi

script:
  - if [ "$BUILD" = "linux"   ]; then PKG_CONFIG_PATH="$(pwd)/TRAVIS_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH" CFLAGS="-I/usr/include/freetype2" make; fi
  - if [ "$BUILD" = "osx"     ]; then make -f src/cocoa/Makefile utox; fi
  - if [ "$BUILD" = "windows" ]; then make dist; fi

notifications:
  email: false
