dist: trusty

language: c

addons:
  apt:
    sources:
       - george-edison55-precise-backports # cmake 3.2.3
    packages:
      - cmake
      - cmake-data
      - dbus
      - dbus-x11
      - libdbus-1-3
      - yasm
      - check
      - libopenal-dev
      - libopenal-data
      - libopenal1
      - libv4l-dev
      - mingw-w64
      - mingw-w64-dev
      - binutils-mingw-w64
      - gcc-mingw-w64

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - env: BUILD=linux TOXCORE_REPO=irungentoo/toxcore
    - env: BUILD=windows
  include:
    - os: linux
      env: BUILD=linux TOXCORE_REPO=TokTok/c-toxcore
      compiler: gcc
    - os: linux
      env: BUILD=linux TOXCORE_REPO=TokTok/c-toxcore
      compiler: clang

    - os: linux
      env: BUILD=linux TOXCORE_REPO=irungentoo/toxcore
      compiler: gcc
    - os: linux
      env: BUILD=linux TOXCORE_REPO=irungentoo/toxcore
      compiler: clang

    - os: linux
      env: BUILD=windows
      compiler: x86_64-w64-mingw32-gcc

    - os: osx
      compiler: clang
      env: BUILD=osx

git:
  depth: 5

before_script:
  - ./travis/env.sh
  - ./travis/${BUILD}-before.sh

script:
  - ./travis/${BUILD}-script.sh

notifications:
  email: false
